steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/backtestalgov1/github.com/ethanmerrill/tradingalgoexperimentation:${_ENVIRONMENT}", "."]
    timeout: "900s"

images:
  - "gcr.io/backtestalgov1/github.com/ethanmerrill/tradingalgoexperimentation:${_ENVIRONMENT}"
